import { Router } from "express";
import authRoutes from "./auth/auth.route.js";
import teacherRoutes from "./teacher/teacher.route.js";
import classRoutes from "./class/class.route.js";
import studentRoutes from "./student/student.route.js";
import categoryRoutes from "./category/category.route.js";
import expenseRoutes from "./expense/expense.route.js";
import staffRoutes from "./staff/staff.route.js";
import subjectRoutes from "./subject/subject.route.js";
import examRoutes from "./exam/exam.route.js";
import attendanceRoutes from "./attendance/attendance.route.js";
import dashboardRoutes from "./dashboard/dashboard.route.js";
import feeRoutes from "./fee/fee.route.js";
import parentRoutes from "./parent/parent.route.js";
import salaryRoutes from "./salary/salary.route.js";
import advanceRoutes from "./advance/advance.route.js";
import examSubjectConfigRoutes from "./exam-subject-config/exam-subject-config.route.js";
import marksRoutes from "./marks/marks.route.js";
import resultPrepRoutes from "./result-prep/result-prep.route.js";
import promotionRoutes from "./promotion/promotion.route.js";
import reportCardRoutes from "./report-card/report-card.routes.js";
import certificateRoutes from "./certificate/certificate.route.js";
import smsRoutes from "./sms/sms.route.js";
import inventoryRoutes from "./inventory/inventory.route.js";
import searchRoutes from "./search/search.route.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/teachers", teacherRoutes);
router.use("/classes", classRoutes);
router.use("/students", studentRoutes);
router.use("/categories", categoryRoutes);
router.use("/expense-categories", categoryRoutes);
router.use("/expenses", expenseRoutes);
router.use("/staff", staffRoutes);
router.use("/subjects", subjectRoutes);
router.use("/exams", examRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/fees", feeRoutes);
router.use("/parents", parentRoutes);
router.use("/salaries", salaryRoutes);
router.use("/advances", advanceRoutes);
router.use("/exam-subject-config", examSubjectConfigRoutes);
router.use("/marks", marksRoutes);
router.use("/result-prep", resultPrepRoutes);
router.use("/promotions", promotionRoutes);
router.use("/report-cards", reportCardRoutes);
router.use("/certificates", certificateRoutes);
router.use("/sms", smsRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/search", searchRoutes);

export default router;
